version: "3"

services:
  twitter_front_react:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - twitter_flask_app

  twitter_flask_app:
    build: ./back
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - twitter_redis

  twitter_redis:
    image: "redis:latest"
    ports:
      - "6379:6379"


