name: checkSyntax
on: [push]
jobs:
  Check-Syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install Flask
      - name: Install dependencies
        run: docker run --name myredis -p 6379:6379 redis
      - name: Check Syntax
        run: python3 main.py check_syntax
