  name: Docker Compose
  on:
    push:
      branches: [ main ]

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: run docker-compose
          uses: sudo-bot/action-docker-compose@latest
          with:
              # https://docs.docker.com/compose/reference/overview/
              cli-args: "up"
